//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: arena_ptr.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

#include "arena_ptr_ptr.h"

namespace arena_ptr {

} // namespace arena_ptr
