//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: ptrpkg.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

#include "ptrpkg_ptr_pmr.h"

namespace ptrpkg_pmr {

} // namespace ptrpkg_pmr
