//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: variants_ptr.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

#include "variants_ptr_ptr_pmr.h"

namespace variants_ptr_pmr {

} // namespace variants_ptr_pmr
