//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: variants.fbe
// FBE version: 1.11.0.0
//------------------------------------------------------------------------------

package variants

import "fmt"
import "strconv"
import "errors"
import "../fbe"

// Workaround for Go unused imports issue
var _ = errors.New
var _ = fbe.Version

// Workaround for Go unused imports issue
var _ = fmt.Print
var _ = strconv.FormatInt

// Expr variant interface
type Expr interface {}

// Create a new Expr struct
func NewExpr() Expr {
    //  TODO(liuqi): keep same with c++ implementation.
    // if the given type is primitive type, use value, otherwise use pointer .
    return false
}
